-- ─── SEED SQL (executado via `supabase db reset`) ──────────────────────────
-- Os USUÁRIOS de teste são criados via `npm run seed:local` (seed.mjs),
-- porque supabase.auth exige entradas em `auth.identities` que INSERT direto
-- em `auth.users` não cria.
--
-- Este arquivo fica reservado para dados que NÃO dependem de auth.
-- Dados demo (pets, consultas, etc) também são criados em seed.mjs.
